#!/bin/bash
set -eoux pipefail

package=api

echo "Checking documentation..."
python3 -m pydocstyle $package
echo "Success!"

echo "Checking code style with black..."
python3 -m black --line-length 90 --check $package
echo "Success!"

echo "Checking code style with pylint..."
python3 -m pylint $package
echo "Success!"

echo "Running unit tests..."
python3 -m pytest
echo "Success!"
